version: "3"
services:
  postgres-king-karel:
    container_name: postgres-king-karel
    image: postgres:12
    environment:
      POSTGRES_USER: karel-bot
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: KingKarel
      TZ: 'Europe/Prague'
      PGTZ: 'Europe/Prague'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
